### ISSUE TITLE
【中文版 WebRTC 1.0官方文档】入口在哪？

### ISSUE THREAD

**Issue by dragonishare** [RTC-Developer/WebRTC-Documentation-in-Chinese#14]
由 **[WebRTC 中文网]** 跳转到github，根据github上的说明，前往 **[RTC 开发者社区] **，到了 **[RTC 开发者社区]** 后，一片荒芜；

这是个**寻宝活动**吗？看个文档而已，都没有**目录或显眼**的链接吗？

**Comment by jeffdzed** [comment]
> 由 **[WebRTC 中文网]** 跳转到github，根据github上的说明，前往 **[RTC 开发者社区] **，到了 **[RTC 开发者社区]** 后，一片荒芜；
> 
> 这是个**寻宝活动**吗？看个文档而已，都没有**目录或显眼**的链接吗？

在「resource」文件夹里，还有一部分没审计完，所以还没把链接明确写在 readme 中。
